[Repo1Changes]
Measure=Plugin
Plugin=RunCommand
Parameter=python check_git_status.py #Repo1Path# local
OutputType=ANSI
UpdateDivider=#60
RegExpSubstitute=1
Substitute="(\d+)\n":"\1"

[Repo1Unpulled]
Measure=Plugin
Plugin=RunCommand
Parameter=python check_git_status.py #Repo1Path# unpulled
OutputType=ANSI
UpdateDivider=#60
RegExpSubstitute=1
Substitute="(\d+)\n":"\1"

[Repo1Unpushed]
Measure=Plugin
Plugin=RunCommand
Program=python.exe
Parameter=check_git_status.py #Repo1Path# unpushed
OutputType=ANSI
UpdateDivider=#60
RegExpSubstitute=1
Substitute="(\d+)\n":"\1"

[Repo2Changes]
Measure=Plugin
Plugin=RunCommand
Parameter=python check_git_status.py #Repo2Path# local
OutputType=ANSI
UpdateDivider=#60
RegExpSubstitute=1
Substitute="(\d+)\n":"\1"

[Repo2Unpulled]
Measure=Plugin
Plugin=RunCommand
Parameter=python check_git_status.py #Repo2Path# unpulled
OutputType=ANSI
UpdateDivider=#60
RegExpSubstitute=1
Substitute="(\d+)\n":"\1"

[Repo2Unpushed]
Measure=Plugin
Plugin=RunCommand
Program=python.exe
Parameter=check_git_status.py #Repo2Path# unpushed
OutputType=ANSI
UpdateDivider=#60
RegExpSubstitute=1
Substitute="(\d+)\n":"\1"

[Repo3Changes]
Measure=Plugin
Plugin=RunCommand
Parameter=python check_git_status.py #Repo3Path# local
OutputType=ANSI
UpdateDivider=#60
RegExpSubstitute=1
Substitute="(\d+)\n":"\1"

[Repo3Unpulled]
Measure=Plugin
Plugin=RunCommand
Parameter=python check_git_status.py #Repo3Path# unpulled
OutputType=ANSI
UpdateDivider=#60
RegExpSubstitute=1
Substitute="(\d+)\n":"\1"

[Repo3Unpushed]
Measure=Plugin
Plugin=RunCommand
Program=python.exe
Parameter=check_git_status.py #Repo3Path# unpushed
OutputType=ANSI
UpdateDivider=#60
RegExpSubstitute=1
Substitute="(\d+)\n":"\1"

[Repo4Changes]
Measure=Plugin
Plugin=RunCommand
Parameter=python check_git_status.py #Repo4Path# local
OutputType=ANSI
UpdateDivider=#60
RegExpSubstitute=1
Substitute="(\d+)\n":"\1"

[Repo4Unpulled]
Measure=Plugin
Plugin=RunCommand
Parameter=python check_git_status.py #Repo4Path# unpulled
OutputType=ANSI
UpdateDivider=#60
RegExpSubstitute=1
Substitute="(\d+)\n":"\1"

[Repo4Unpushed]
Measure=Plugin
Plugin=RunCommand
Program=python.exe
Parameter=check_git_status.py #Repo4Path# unpushed
OutputType=ANSI
UpdateDivider=#60
RegExpSubstitute=1
Substitute="(\d+)\n":"\1"

[Repo5Changes]
Measure=Plugin
Plugin=RunCommand
Parameter=python check_git_status.py #Repo5Path# local
OutputType=ANSI
UpdateDivider=#60
RegExpSubstitute=1
Substitute="(\d+)\n":"\1"

[Repo5Unpulled]
Measure=Plugin
Plugin=RunCommand
Parameter=python check_git_status.py #Repo5Path# unpulled
OutputType=ANSI
UpdateDivider=#60
RegExpSubstitute=1
Substitute="(\d+)\n":"\1"

[Repo5Unpushed]
Measure=Plugin
Plugin=RunCommand
Program=python.exe
Parameter=check_git_status.py #Repo5Path# unpushed
OutputType=ANSI
UpdateDivider=#60
RegExpSubstitute=1
Substitute="(\d+)\n":"\1"

[Repo6Changes]
Measure=Plugin
Plugin=RunCommand
Parameter=python check_git_status.py #Repo6Path# local
OutputType=ANSI
UpdateDivider=#60
RegExpSubstitute=1
Substitute="(\d+)\n":"\1"

[Repo6Unpulled]
Measure=Plugin
Plugin=RunCommand
Parameter=python check_git_status.py #Repo6Path# unpulled
OutputType=ANSI
UpdateDivider=#60
RegExpSubstitute=1
Substitute="(\d+)\n":"\1"

[Repo6Unpushed]
Measure=Plugin
Plugin=RunCommand
Program=python.exe
Parameter=check_git_status.py #Repo6Path# unpushed
OutputType=ANSI
UpdateDivider=#60
RegExpSubstitute=1
Substitute="(\d+)\n":"\1"

[Repo7Changes]
Measure=Plugin
Plugin=RunCommand
Parameter=python check_git_status.py #Repo7Path# local
OutputType=ANSI
UpdateDivider=#60
RegExpSubstitute=1
Substitute="(\d+)\n":"\1"

[Repo7Unpulled]
Measure=Plugin
Plugin=RunCommand
Parameter=python check_git_status.py #Repo7Path# unpulled
OutputType=ANSI
UpdateDivider=#60
RegExpSubstitute=1
Substitute="(\d+)\n":"\1"

[Repo7Unpushed]
Measure=Plugin
Plugin=RunCommand
Program=python.exe
Parameter=check_git_status.py #Repo7Path# unpushed
OutputType=ANSI
UpdateDivider=#60
RegExpSubstitute=1
Substitute="(\d+)\n":"\1"

[Repo8Changes]
Measure=Plugin
Plugin=RunCommand
Parameter=python check_git_status.py #Repo8Path# local
OutputType=ANSI
UpdateDivider=#60
RegExpSubstitute=1
Substitute="(\d+)\n":"\1"

[Repo8Unpulled]
Measure=Plugin
Plugin=RunCommand
Parameter=python check_git_status.py #Repo8Path# unpulled
OutputType=ANSI
UpdateDivider=#60
RegExpSubstitute=1
Substitute="(\d+)\n":"\1"

[Repo8Unpushed]
Measure=Plugin
Plugin=RunCommand
Program=python.exe
Parameter=check_git_status.py #Repo8Path# unpushed
OutputType=ANSI
UpdateDivider=#60
RegExpSubstitute=1
Substitute="(\d+)\n":"\1"

[Repo9Changes]
Measure=Plugin
Plugin=RunCommand
Parameter=python check_git_status.py #Repo9Path# local
OutputType=ANSI
UpdateDivider=#60
RegExpSubstitute=1
Substitute="(\d+)\n":"\1"

[Repo9Unpulled]
Measure=Plugin
Plugin=RunCommand
Parameter=python check_git_status.py #Repo9Path# unpulled
OutputType=ANSI
UpdateDivider=#60
RegExpSubstitute=1
Substitute="(\d+)\n":"\1"

[Repo9Unpushed]
Measure=Plugin
Plugin=RunCommand
Program=python.exe
Parameter=check_git_status.py #Repo9Path# unpushed
OutputType=ANSI
UpdateDivider=#60
RegExpSubstitute=1
Substitute="(\d+)\n":"\1"

[Repo10Changes]
Measure=Plugin
Plugin=RunCommand
Parameter=python check_git_status.py #Repo10Path# local
OutputType=ANSI
UpdateDivider=#60
RegExpSubstitute=1
Substitute="(\d+)\n":"\1"

[Repo10Unpulled]
Measure=Plugin
Plugin=RunCommand
Parameter=python check_git_status.py #Repo10Path# unpulled
OutputType=ANSI
UpdateDivider=#60
RegExpSubstitute=1
Substitute="(\d+)\n":"\1"

[Repo10Unpushed]
Measure=Plugin
Plugin=RunCommand
Program=python.exe
Parameter=check_git_status.py #Repo10Path# unpushed
OutputType=ANSI
UpdateDivider=#60
RegExpSubstitute=1
Substitute="(\d+)\n":"\1"